config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # List all tasks
  get '/tasks', to: 'tasks#index'

  # Add new task
  get '/tasks/new', to: 'tasks#new', as: :create_task
  post '/tasks', to: 'tasks#create'

  # View the details of the task
  get '/tasks/:id', to: 'tasks#show', as: :task

  # Edit a task
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'

  # Delete task
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [ :show, :edit, :update, :destroy ]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(set_task)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(set_task)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def set_task
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/406e275bc8.js" crossorigin="anonymous"></script>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

<p><%= link_to "Back to tasks", tasks_path %></p>

app/views/tasks/index.html.erb
<%# <head>
<script src="https://kit.fontawesome.com/406e275bc8.js" crossorigin="anonymous"></script>

</head> %>


<h1>All your tasks:</h1>
<% @tasks.each do |task| %>

  <h2><%= link_to task.title, task_path(task) %></h2>

  <% if task.completed %>
    <i class="fa-regular fa-square-check"></i>
  <% else %>
    <i class="fa-regular fa-square"></i>
  <% end %>

<% end %>

<p><%= link_to "Create task", create_task_path %></p>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

<p><%= link_to "Back to tasks", tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<p><%= link_to "Back to tasks", tasks_path %></p>
<p><%= link_to "Edit", edit_task_path(@task) %></p>
<p><%= link_to "Delete", delete_task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %></p>